export enum RouterPaths {
  home = '/',
  about = '/about',
  productList = '/collections',
  productDetail = '/products',
  login = '/login',
  register = '/register',
  forgot = '/forgot',
  activation = '/activation',
  reset = '/reset',
  myaccount = '/myaccount',
  cart = '/cart',
  orders = '/orders',
  admin = '/admin',
}
