import { fbEvent } from '@rivercode/facebook-conversion-api-nextjs';

import type { CartItem } from '@core/types/cart';
import type { ProductInventory } from '@core/types/products';

export const sendAddToCartFBEvent = (cartItem: CartItem) => {
  let inventories: ProductInventory[] = [];
  if (cartItem.inventory) {
    inventories.push(cartItem.inventory);
  } else if (cartItem.pack) {
    inventories = cartItem.pack.inventories;
  };
  const productsEvent = inventories.map((item) => {
    return {
      sku: item.sku,
      quantity: item.quantity,
    };
  });

  fbEvent({
    eventName: 'AddToCart', // ViewContent, AddToCart, InitiateCheckout or Purchase
    //eventId: 'eventId', // optional, unique event id's will be generated by default
    //emails: ['email1', 'email2'], // optional
    //phones: ['phone1', 'phone2'], // optional
    products: productsEvent,
    //value: 1000, // optional
    //currency: 'USD', // optional
    //enableStandardPixel: false // default false (Require Facebook Pixel to be loaded, see step 2)
  });
}