export type FacebookEvent = {
  eventName: string,
  eventId?: string, // optional, unique event id's will be generated by default
  emails?: string[],
  phones?: string[],
  products: {
    sku: string
    quantity: number
  }[],
  value?: number,
  currency?: string,
};
